server:
  port: ${PORT:${SERVER_PORT:8081}}
spring:
  application:
    name: htp-frontend-service
  profiles:
    active: qa

---
spring:
  config:
    activate:      on-profile: dev
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:mysql://localhost:3306/tri_polymer_frontend
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/tri_polymer_frontend
    username: root
    password: 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

---
app:
  jwtSecret: triPolymerSecretKey
  jwtExpirationMs: 86400000
