server:
  port: ${PORT:${SERVER_PORT:8081}}
spring:
  application:
    name: tri-polymer-online
  devtools:
    add-properties: false

logging:
  level:
    web: DEBUG
    root: INFO

---
spring:
  config:
    activate:      on-profile: development
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/tri_polymer_online
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
