server:
  port: ${PORT:${SERVER_PORT:8080}}
spring:
  application:
    name: tri-polymer-online
  devtools:
    add-properties: false
  main:
    allow-circular-reference: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    web: DEBUG
    root: INFO

---
spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password: 
